# Generated by Django 4.1.7 on 2023-02-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='texts',
            name='rzd_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
