# Generated by Django 4.1.7 on 2023-03-03 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_texts_rzd_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='texts',
            name='rzd_image',
        ),
    ]
