# Generated by Django 4.1.7 on 2023-03-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_texts_rzd_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='texts',
            name='checked_by_human',
            field=models.IntegerField(default=0, verbose_name='Проверка проведена человеком'),
            preserve_default=False,
        ),
    ]
