# Generated by Django 4.1.7 on 2023-03-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_texts_checked_by_human'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texts',
            name='theme',
            field=models.CharField(default='', max_length=1000, verbose_name='Тема'),
        ),
    ]
