# Generated by Django 4.1.7 on 2023-03-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_texts_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelhist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.FloatField(default=0.0, verbose_name='Точность')),
            ],
        ),
    ]
