# Generated by Django 4.1.7 on 2023-03-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_modelhist'),
    ]

    operations = [
        migrations.AddField(
            model_name='texts',
            name='text_accuracy',
            field=models.FloatField(default=0.0, verbose_name='Точность'),
        ),
        migrations.AddField(
            model_name='texts',
            name='uploaded',
            field=models.IntegerField(default=0, verbose_name='Загружено через файл'),
        ),
    ]
