# Generated by Django 4.1.7 on 2023-03-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_texts_text_accuracy_texts_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='texts',
            name='eof',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='texts',
            name='existingPath',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='texts',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
