# Generated by Django 4.1.7 on 2023-03-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_texts_eof_texts_existingpath_texts_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='texts',
            name='resumes',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='texts',
            name='existingPath',
            field=models.CharField(max_length=100),
        ),
    ]
