# Generated by Django 4.1.7 on 2023-03-13 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_texts_resumes_alter_texts_existingpath'),
    ]

    operations = [
        migrations.RenameField(
            model_name='texts',
            old_name='resumes',
            new_name='text_file',
        ),
        migrations.RemoveField(
            model_name='texts',
            name='eof',
        ),
        migrations.RemoveField(
            model_name='texts',
            name='existingPath',
        ),
        migrations.RemoveField(
            model_name='texts',
            name='name',
        ),
    ]
