# Generated by Django 4.1.7 on 2023-03-27 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_texts_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelhist',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
