# Generated by Django 4.1.7 on 2023-03-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_modelhist_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelhist',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата обучения'),
        ),
    ]
