# Generated by Django 4.1.7 on 2023-03-27 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_modelhist_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelhist',
            name='date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Дата обучения'),
        ),
    ]
