# Generated by Django 4.1.7 on 2023-03-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_modelhist_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelhist',
            name='date',
            field=models.DateField(default='2023-03-27', verbose_name='Дата обучения'),
        ),
    ]
