# Generated by Django 4.1.7 on 2023-04-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_modelhist_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texts',
            name='checked_by_human',
            field=models.IntegerField(choices=[(0, 0), (1, 1)], default=0, verbose_name='Проверка проведена человеком'),
        ),
    ]
