# Generated by Django 4.1.7 on 2023-04-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_texts_checked_by_human'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texts',
            name='checked_by_human',
            field=models.IntegerField(choices=[(0, 'Нет'), (1, 'Да')], default=0, verbose_name='Проверка проведена человеком'),
        ),
    ]
