# Generated by Django 4.1.7 on 2023-05-16 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_modelhist_modeltype_alter_modelhist_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelhist',
            name='modeltype',
            field=models.IntegerField(default=1),
        ),
    ]
